# -*- coding: utf-8 -*-
"""data visualization.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11KFtBP_bT0w8D31XskTxbuVtbCTZ4wsQ
"""

import requests
from bs4 import BeautifulSoup
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import re

# STEP 1: Scrape data from website
url = "http://books.toscrape.com/"
response = requests.get(url)
soup = BeautifulSoup(response.text, 'html.parser')
books = soup.find_all('article', class_='product_pod')

data = []
for book in books:
    title = book.h3.a['title']
    price = book.find('p', class_='price_color').text
    data.append({'Title': title, 'Price': price})

# STEP 2: Convert to DataFrame
df = pd.DataFrame(data)

# STEP 3: Clean the Price column
def clean_price(price_str):
    return float(re.sub(r'[^\d.]', '', str(price_str)))

df['Price'] = df['Price'].apply(clean_price)

# STEP 4: Set visual style
sns.set(style='whitegrid')

# STEP 5: Histogram - Price distribution
plt.figure(figsize=(10, 6))
sns.histplot(df['Price'], bins=10, kde=True, color='skyblue')
plt.title('Distribution of Book Prices')
plt.xlabel('Price (£)')
plt.ylabel('Number of Books')
plt.tight_layout()
plt.show()

"""Please upload the `books.csv` file when prompted."""

from google.colab import files
uploaded = files.upload()